import { ActasState } from "./types";

export const LISTA_DOCUMENTOS = [
  { id: "intervencion", title: "Acta de Intervención Policial", cppArticle: "Vulneraciones / Hechos Generales", pages: "Pág. 1" },
  { id: "detencion", title: "Notificación de Detención", cppArticle: "Art. 120.4 CPP / Art. 71.2 CPP", pages: "Pág. 2" },
  { id: "buenTrato", title: "Constancia de Buen Trato", cppArticle: "Respeto a DDHH", pages: "Pág. 3" },
  { id: "registroPersonal", title: "Acta de Registro Personal e Incautación", cppArticle: "Art. 210 CPP", pages: "Pág. 7-8" },
  { id: "registroVehicular", title: "Acta de Registro Vehicular", cppArticle: "Art. 210 CPP", pages: "Pág. 9-10" },
  { id: "situacionVehicular", title: "Acta de Situación Vehicular", cppArticle: "Inspección de Estado de Vehículo", pages: "Pág. 11-12" },
  { id: "recepcion", title: "Acta de Recepción", cppArticle: "Entrega Voluntaria u Objetos", pages: "Pág. 15-16" },
  { id: "incautacionArt203", title: "Acta de Incautación (Art. 203 NCPP)", cppArticle: "Art. 203.3 NCPP / Ac. Plenario 5-2010", pages: "Pág. 18" },
  { id: "entregaRecepcionMenor", title: "Acta de Entrega y Recepción de Menor", cppArticle: "Interés Superior / DL 1348 / DL 1297", pages: "Pág. 17" },
  { id: "lacradoArma", title: "Acta de Lacrado de Arma de Fuego", cppArticle: "Lacrado de Arma e Indicios", pages: "Pág. 14" },
  { id: "ocurrencia", title: "Parte de Ocurrencia", cppArticle: "Hechos Diversos / Ocurrencias", pages: "Pág. 19" },
  { id: "rotuloEvidencias", title: "Rótulo de Indicios y Evidencias", cppArticle: "En Cadena de Custodia", pages: "Pág. 20" },
  { id: "cadenaCustodia", title: "Acta de Cadena de Custodia", cppArticle: "Continuidad de Custodia", pages: "Pág. 13" }
];

export const INITIAL_STATE: ActasState = {
  police: {
    lugarCiudad: "",
    distrito: "",
    provincia: "",
    fecha: "",
    hora: "",
    instructorNombres: "",
    instructorApellidos: "",
    instructorGrado: "",
    instructorCIP: "",
    companiaDe: "",
    unidadPolicial: ""
  },
  detenido: {
    nombres: "",
    apellidos: "",
    dni: "",
    naturalDe: "",
    nacidoEl: "",
    estadoCivil: "",
    ocupacion: "",
    gradoInstruccion: "",
    domiciliadoEn: "",
    celular: "",
    correo: "",
    sexo: "M",
    edad: "",
    tipo: "DETENIDO",
    nacionalidad: ""
  },
  activeDocuments: ["intervencion"],
  currentDocId: "intervencion",
  intervencion: {
    circunstanciasPrecedentes: "",
    circunstanciasConcomitantes: "",
    circunstanciasPosteriores: "",
    horaConcluida: "",
    fechaConcluida: "",
    registroPersonalRealizado: false,
    lecturaDerechosRealizado: false,
    lacradoInmovilizacionRealizado: false,
    cadenaCustodiaRealizado: false
  },
  detencion: {
    delitoFlagranteContexto: "",
    horaConcluida: "",
    fechaConcluida: ""
  },
  buenTrato: {
    recibioBuenTrato: true,
    horaFirma: "",
    fechaFirma: ""
  },
  comunicacionTelefonica: {
    equipoEmpleado: "Celular",
    telFijo: "",
    telCelular: "",
    garantizaDerechoDe: "",
    celularOperador: "",
    marcaCaracteristica: "",
    propiedadDe: "",
    numeroLlamado: "",
    operadorLlamado: "",
    fechaHoraLlamada: "",
    recibeLlamada: "",
    parentesco: "",
    duracionHoras: "",
    duracionMin: "",
    duracionSeg: "",
    grabacionLlamada: "NO",
    capturaPantalla: "NO",
    resultadoComunicacion: "",
    horaConcluida: "",
    fechaConcluida: ""
  },
  detencionMenor: {
    pertenecienteA: "",
    padreNombre: "",
    madreNombre: "",
    motivoInfraccionLeyes: "",
    contactoPadreNombre: "",
    contactoPadreVinculo: "",
    contactoPadreDniEnabled: "SI",
    contactoPadreDni: "",
    contactoPadreCelular: "",
    contactoPadreObs: "",
    contactoFiscalNombre: "",
    contactoFiscalia: "",
    contactoFiscalCargo: "",
    contactoFiscalCelular: "",
    contactoFiscalObs: "",
    contactoJuezNombre: "",
    contactoJuezJuzgado: "",
    contactoJuezCargo: "",
    contactoJuezCelular: "",
    contactoJuezObs: "",
    numCelularUsado: "",
    operadorCelularUsado: "",
    marcaCelularUsada: "",
    propiedadCelularUsada: "",
    horaConcluida: "",
    fechaConcluida: "",
    detenidosAdicionales: []
  },
  registroPersonal: {
    lugarRegistro: "",
    hijoDeDon: "",
    hijoDeDona: "",
    solicitadoExhibirBienes: "",
    personalLlevaACabo: "",
    drogasInsumosCheck: false,
    drogasInsumosDetalle: "",
    billetesMonedasCheck: false,
    billetesMonedasDetalle: "",
    municionArmasCheck: false,
    municionArmasDetalle: "",
    otrosInteresCheck: false,
    otrosInteresDetalle: "",
    dejaConstancia: "",
    horaConcluida: "",
    fechaConcluida: ""
  },
  registroVehicular: {
    personasEnVehiculo: "",
    solicitudExhibicion: "NEGATIVO",
    descripcionBienExhibido: "",
    placa: "",
    marca: "",
    color: "",
    modelo: "",
    anioFabricacion: "",
    otrosDetalleVehiculo: "",
    razonesRegistro: "",
    testigoNombres: "",
    testigoIdentificadoDni: "",
    testigoDomiciliadoEn: "",
    testigoCelular: "",
    testigoParentesco: "",
    bienesObjetoRegistro: "",
    filmacionMedio: "",
    razonesNoLevantarEnLugar: "",
    negativaFirmarRazon: "",
    horaConcluida: "",
    fechaConcluida: ""
  },
  situacionVehicular: {
    datosGenerales: {
      placa: "",
      clase: "",
      color: "",
      marcaModelo: "",
      motorNo: "",
      serieChasis: "",
      estadoConservacion: "",
      tipoVehiculo: "MAYOR"
    },
    partesExteriores: {
      faroGrandeDelantero: "NO_REGISTRA",
      faroChicoDelantero: "NO_REGISTRA",
      farosPosteriores: "NO_REGISTRA",
      biseles: "NO_REGISTRA",
      limpiaParabrisas: "NO_REGISTRA",
      llantas: "NO_REGISTRA",
      vasos: "NO_REGISTRA",
      espejoExterior: "NO_REGISTRA",
      chapas: "NO_REGISTRA",
      antenas: "NO_REGISTRA",
      parachoques: "NO_REGISTRA",
      llantasRepuesto: "NO_REGISTRA",
      parabrisas: "NO_REGISTRA"
    },
    partesInteriores: {
      tablero: "NO_REGISTRA",
      chapaContacto: "NO_REGISTRA",
      radio: "NO_REGISTRA",
      encendedor: "NO_REGISTRA",
      pisos: "NO_REGISTRA",
      manijas: "NO_REGISTRA",
      ceniceros: "NO_REGISTRA",
      parasoles: "NO_REGISTRA",
      espejoInterior: "NO_REGISTRA",
      coderas: "NO_REGISTRA",
      gata: "NO_REGISTRA",
      llaveRuedas: "NO_REGISTRA",
      parlante: "NO_REGISTRA",
      asientos: "NO_REGISTRA"
    },
    motorAccesorios: {
      motor: "NO_REGISTRA",
      bateria: "NO_REGISTRA",
      arrancador: "NO_REGISTRA",
      carburador: "NO_REGISTRA",
      distribuidor: "NO_REGISTRA",
      tapaAceite: "NO_REGISTRA",
      chicotes: "NO_REGISTRA",
      radiador: "NO_REGISTRA",
      alternador: "NO_REGISTRA",
      purificador: "NO_REGISTRA",
      bobina: "NO_REGISTRA",
      bujias: "NO_REGISTRA",
      varillaAceite: "NO_REGISTRA"
    },
    descripcionEspecificaCompleta: "",
    perennizacionMedio: "",
    observaciones: "",
    negativaFirmarRazon: "",
    fechaConcluida: "",
    horaConcluida: "",
    intervenidoPadreNombre: "",
    intervenidoMadreNombre: "",
    lugarInspeccion: "",
    detenidosAdicionales: []
  },
  registroEquipajes: {
    solicitudExhibicion: "NEGATIVO",
    descripcionBienExhibido: "",
    placaVehiculoAsociado: "",
    marcaVehiculoAsociado: "",
    colorVehiculoAsociado: "",
    modeloVehiculoAsociado: "",
    anioVehiculoAsociado: "",
    otrosVehiculoAsociado: "",
    razonesRegistro: "",
    testigoNombres: "",
    testigoIdentificadoDni: "",
    testigoDomiciliadoEn: "",
    testigoCelular: "",
    testigoParentesco: "",
    apremianteSexoDistinto: "",
    bienesObjetoRegistro: "",
    filmacionMedio: "",
    razonesNoLevantarEnLugar: "",
    negativaFirmarRazon: "",
    horaConcluida: "",
    fechaConcluida: ""
  },
  recepcion: {
    personaNombres: "",
    personaApellidos: "",
    personaGradoInstruccion: "",
    personaDni: "",
    personaSexo: "M",
    personaEdad: "",
    personaTelefono: "",
    personaCelular: "",
    personaParentescoReferencia: "",
    personaDomicilio: "",
    personaNacionalidad: "",
    personaOcupacion: "",
    personaTrabajo: "",
    razonesEntrega: "",
    descripcionBienObjeto: "",
    perennizacionRecepcion: "",
    funcionarioCustodia: "",
    negativaFirmarRazon: "",
    horaConcluida: "",
    fechaConcluida: ""
  },
  ocurrencia: {
    asunto: "",
    detallesOcurrencia: "",
    medidasAdoptadas: "",
    horaConcluida: "",
    fechaConcluida: ""
  },
  rotuloEvidencias: {
    codigoCarpetaFiscal: "",
    prioridad: "",
    distritoJudicial: "",
    numHallazgo: "",
    cantidad: "",
    unidadMedida: "",
    dependenciaInterviene: "",
    lugarRecoleccion: "",
    fechaRecoleccion: "",
    horaRecoleccion: "",
    descripcionCondicion: "",
    tipoEmbalaje: "",
    servidorNombres: "",
    servidorDniCip: "",
    servidorCargo: "",
    fechaEmbalaje: "",
    horaEmbalaje: "",
    rpm: ""
  },
  cadenaCustodia: {
    codigoCarpetaFiscal: "",
    distritoJudicial: "",
    prioridad: "",
    descripcionBienIncautado: "",
    quienEmbala: "",
    quienTransporta: "",
    dniCipInicial: "",
    cargoInicial: "",
    fechaInicial: "",
    horaInicial: "",
    registrosContinuidad: []
  },
  incautacionArt203: {
    vincularConPrincipal: true,
    situacionPersona: "INTERVENIDO",
    lugarIncautacion: "",
    intervenidoNombre: "",
    intervenidoEdad: "",
    intervenidoNaturalDe: "",
    intervenidoEstadoCivil: "",
    intervenidoPadreNombre: "",
    intervenidoMadreNombre: "",
    intervenidoOcupacion: "",
    intervenidoInstruccion: "",
    intervenidoDni: "",
    intervenidoDomicilio: "",
    intervenidoCelular: "",
    testigoNombre: "",
    testigoEdad: "",
    testigoNaturalDe: "",
    testigoEstadoCivil: "",
    testigoPadreNombre: "",
    testigoMadreNombre: "",
    testigoOcupacion: "",
    testigoInstruccion: "",
    testigoDni: "",
    testigoDomicilio: "",
    testigoCelular: "",
    detalleIncautacion: "",
    horaConcluida: "",
    fechaConcluida: "",
    detenidosAdicionales: []
  },
  entregaRecepcionMenor: {
    lugarUbicado: "",
    receptorNombreCompleto: "",
    receptorEdad: "",
    receptorNaturalDe: "",
    receptorEstadoCivil: "",
    receptorPadre: "",
    receptorMadre: "",
    receptorOcupacion: "",
    receptorInstruccion: "",
    receptorDni: "",
    receptorDomicilio: "",
    receptorCelular: "",
    parentescoConMenor: "",
    menorNombreCompleto: "",
    menorDni: "",
    circunstanciasEntrega: "",
    horaConcluida: "",
    fechaConcluida: "",
    detenidosAdicionales: []
  },
  lacradoArma: {
    oficinaPoneALavista: "",
    armaIncautadaAlDetenido: "",
    actaConsta: "",
    fechaActaConsta: "",
    horaActaConsta: "",
    suscriptoresActaConsta: "",
    dejaConstanciaPuestoALavista: "",
    tipoEmbalajeIntroducido: "",
    horaConcluida: ""
  }
};
